// AUTH
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';

export const AUTH_LOGOUT_START = 'AUTH_LOGOUT_START';
export const AUTH_LOGOUT_FAIL = 'AUTH_LOGOUT_FAIL';
export const AUTH_LOGOUT_SUCCESS = 'AUTH_LOGOUT_SUCCESS';

export const AUTH_GET_TOKEN_START = 'AUTH_GET_TOKEN_START';
export const AUTH_GET_TOKEN_SUCCESS = 'AUTH_GET_TOKEN_SUCCESS';

// PROFILE
export const PROFILE_START = 'PROFILE_START';
export const PROFILE_FAIL = 'PROFILE_FAIL';
export const PROFILE_SUCCESS = 'PROFILE_SUCCESS';

// EXPERIENCE
export const EXPERIENCE_START = 'EXPERIENCE_START';
export const EXPERIENCE_FAIL = 'EXPERIENCE_FAIL';
export const EXPERIENCE_SUCCESS = 'EXPERIENCE_SUCCESS';

// EDUCATION
export const EDUCATION_START = 'EDUCATION_START';
export const EDUCATION_FAIL = 'EDUCATION_FAIL';
export const EDUCATION_SUCCESS = 'EDUCATION_SUCCESS';

